version: '3'
services:
  frontend:
    build:
      context: .
    image: get-parked-frontend
    command: npm start
    ports:
      - "3001:3001"
      - "8002:8002"
    volumes:
      - .:/app
  backend:
    build:
      context: ./backend
    image: get-parked-backend
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      SERVER_PORT: 8080
      SERVER_HOST: "0.0.0.0"
      DATABASE_HOST: "database"
      MYSQL_ROOT_PASSWORD: "mysql"
  database:
    image: "mysql:5.7"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d