curl 'http://127.0.0.1:8080/api/new-account' -H 'Accept: */*' -H 'Referer: http://localhost:8002/new-account.html' -H 'Origin: http://localhost:8002' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36' -H 'Sec-Fetch-Mode: cors' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data 'fullName=1&mobile=2&email=3&password=4&passwordRepeat=5' --compressed
